### ISSUE TITLE
[BUG] Pure black in display/dark theme

### ISSUE THREAD

**Issue by Sleppyiecat** [ProjectSakura/Bug_Tracker#23]
**About the Bug.**
Well it's not working, needs to change it in sakura settings

**How to reproduce it.**

1. go to settings -> display -> dark theme (click on it) -> click "pure black"
2. well it won't change, to change it to black needs to go to sakura seetings

**Expected behaviour of the feature without bug.**

should turn system settings to black instead of dark

**Screenshots if applicable**

https://prnt.sc/10lfj4c

**Comment by LordShenron** [comment]
No, when you turn on the pitch black toggle in display settings it won't get applied until you turn on dark mode itself. It's more like an alternative to normal dark mode. So, this is not classified as a bug. 

Also, soon enough the dark theme toggle from display settings and accessibility settings will be removed because it is an ambiguity at the end we have 3 ways of enabling dark mode and it's not good.

**Comment by Sleppyiecat** [comment]
Pro
